from __future__ import annotations

import json
import os
import re
import sqlite3
import unicodedata
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from nutrimaster.rag.bm25 import tokenize

FIELD_KEYWORD_INDEX_VERSION = "v3-sqlite-dual-fts"

SPECIAL_FIELDS = {
    "content": "__content__",
    "text": "__content__",
    "paper_title": "__paper_title__",
    "title": "__paper_title__",
    "journal": "__journal__",
    "doi": "__doi__",
    "gene_name": "Gene_Name",
    "gene": "Gene_Name",
    "relations": "__relations__",
    "relation": "__relations__",
    "source_fields": "__source_fields__",
    "chunk_type": "__chunk_type__",
    "gene_type": "__gene_type__",
}

DEFAULT_TARGET_FIELDS = {
    "Gene_Name": 2.6,
    "Enzyme_Name": 2.2,
    "Terminal_Metabolite": 2.4,
    "Terminal_Metabolite_Class": 1.5,
    "Primary_Substrate": 2.2,
    "Primary_Product": 2.4,
    "Catalyzed_Reaction_Description": 1.9,
    "Biosynthetic_Pathway": 1.8,
    "Pathway_Branch_or_Subpathway": 1.5,
    "Metabolic_Step_Position": 1.3,
    "Rate_Limiting_or_Key_Control_Step": 1.6,
    "Regulation_Mode": 1.5,
    "Metabolic_Process_Controlled": 1.6,
    "Primary_Regulatory_Targets": 1.8,
    "Regulatory_Effect_on_Target_Genes": 1.5,
    "Protein_Complex_Involvement": 1.4,
    "Interacting_Proteins": 1.4,
    "Source_Species": 1.2,
    "Source_Species_Latin_Name": 1.4,
    "Applied_Species": 1.2,
    "Applied_Species_Latin_Name": 1.4,
    "Summary_Key_Findings_of_Core_Gene": 1.0,
    "Core_Phenotypic_Effect": 1.0,
    "Other_Important_Info": 0.9,
    "Potential_Tradeoffs": 0.9,
    "paper_title": 0.7,
    "content": 0.35,
}

INVALID_VALUES = {"", "-", "na", "n/a", "none", "null", "nan", "unknown", "not available"}
MAX_CONCEPTS = 32
MAX_SURFACE_FORMS = 128
MAX_TARGET_FIELDS_PER_CONCEPT = 64
MAX_SURFACE_TEXT_CHARS = 256
MAX_COHIT_TERMS_PER_FORM = 16


@dataclass(frozen=True)
class SurfaceForm:
    """One grep-like candidate generated for a query concept.

    ``text`` is the literal string to search. ``weight`` is local reliability:
    broad abbreviations such as "GA" should be much lower than specific phrases.
    ``match`` is intentionally limited to non-regex strategies so agent output
    cannot inject expensive or unsafe regular expressions.
    """

    text: str
    weight: float = 1.0
    match: str = "phrase"
    requires_cohit: tuple[str, ...] = ()


@dataclass(frozen=True)
class ConceptSpec:
    """A user-query concept with query importance and schema field priorities."""

    concept: str
    query_weight: float = 1.0
    surface_forms: tuple[SurfaceForm, ...] = ()
    target_fields: dict[str, float] = field(default_factory=dict)
    concept_cap_multiplier: float = 2.0


@dataclass(frozen=True)
class FieldKeywordSpec:
    """Complete field-keyword search spec, usually generated by the agent."""

    concepts: tuple[ConceptSpec, ...]
    occurrence_decay: float = 0.5
    max_occurrences_per_field: int = 8


@dataclass(frozen=True)
class FieldKeywordRecord:
    """Normalized searchable projection of a GeneChunk."""

    fields: dict[str, str]
    all_text: str


@dataclass(frozen=True)
class FieldKeywordMatch:
    """Debug information for one concept hit inside one chunk."""

    concept: str
    field: str
    surface_form: str
    count: int
    score: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "concept": self.concept,
            "field": self.field,
            "surface_form": self.surface_form,
            "count": self.count,
            "score": self.score,
        }


class FieldKeywordRetriever:
    """Schema-aware scorer backed by a disk-resident SQLite FTS index.

    This is a complement to dense embeddings and BM25. It is deliberately
    fielded: matching "glycyrrhetinic acid" in Terminal_Metabolite should count
    more than matching it once in generic rendered content.

    The previous pickle duplicated every metadata/content string into Python
    objects and again into ``all_text``.  On the production corpus that added
    more than a gigabyte of heap.  The contentless FTS index stores postings but
    not another copy of the text.  FTS only generates a superset of candidates;
    the existing Python scorer reconstructs those candidates from canonical
    ``GeneChunk`` objects and performs the exact phrase/token/co-hit calculation.
    """

    def __init__(self, index_path: Path, chunks: list[Any] | None = None):
        self.index_path = Path(index_path)
        self._chunks = chunks
        self.n_chunks = 0
        self.corpus_fingerprint: str | None = None
        self.version = FIELD_KEYWORD_INDEX_VERSION
        self._staged_path: Path | None = None

    @property
    def path(self) -> Path:
        return self.index_path / "field_keyword_v3.sqlite3"

    def build(self, chunks: list[Any], *, corpus_fingerprint: str | None = None) -> None:
        self.index_path.mkdir(parents=True, exist_ok=True)
        staged_path = self.path.with_name(f".{self.path.name}.{os.getpid()}.{id(self)}.tmp")
        staged_path.unlink(missing_ok=True)

        connection = sqlite3.connect(staged_path)
        try:
            connection.execute("PRAGMA journal_mode=OFF")
            connection.execute("PRAGMA synchronous=OFF")
            connection.execute("PRAGMA temp_store=FILE")
            connection.execute("PRAGMA cache_size=-32768")
            connection.executescript(
                """
                CREATE TABLE metadata (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                ) WITHOUT ROWID;
                CREATE TABLE field_rows (
                    rowid INTEGER PRIMARY KEY,
                    chunk_id INTEGER NOT NULL,
                    field_name TEXT NOT NULL
                );
                CREATE VIRTUAL TABLE field_fts USING fts5(
                    field_text,
                    content='',
                    tokenize='trigram'
                );
                CREATE VIRTUAL TABLE field_token_fts USING fts5(
                    field_text,
                    content='',
                    tokenize='unicode61 remove_diacritics 2'
                );
                """
            )

            rowid = 0
            mapping_rows: list[tuple[int, int, str]] = []
            fts_rows: list[tuple[int, str]] = []

            def flush_rows() -> None:
                if not mapping_rows:
                    return
                connection.executemany(
                    "INSERT INTO field_rows(rowid, chunk_id, field_name) VALUES (?, ?, ?)",
                    mapping_rows,
                )
                connection.executemany(
                    "INSERT INTO field_fts(rowid, field_text) VALUES (?, ?)",
                    fts_rows,
                )
                connection.executemany(
                    "INSERT INTO field_token_fts(rowid, field_text) VALUES (?, ?)",
                    fts_rows,
                )
                mapping_rows.clear()
                fts_rows.clear()

            for chunk_id, chunk in enumerate(chunks):
                record = _record_from_chunk(chunk)
                for field_name, field_text in record.fields.items():
                    if not field_text:
                        continue
                    rowid += 1
                    mapping_rows.append((rowid, chunk_id, field_name))
                    fts_rows.append((rowid, field_text))
                    if len(mapping_rows) >= 10_000:
                        flush_rows()
                if chunk_id and chunk_id % 1000 == 0:
                    flush_rows()
                    connection.commit()
            flush_rows()

            connection.executescript(
                """
                CREATE INDEX field_rows_by_name ON field_rows(field_name, chunk_id);
                INSERT INTO field_fts(field_fts) VALUES('optimize');
                INSERT INTO field_token_fts(field_token_fts) VALUES('optimize');
                INSERT INTO field_fts(field_fts) VALUES('integrity-check');
                INSERT INTO field_token_fts(field_token_fts) VALUES('integrity-check');
                """
            )
            connection.executemany(
                "INSERT INTO metadata(key, value) VALUES (?, ?)",
                [
                    ("version", FIELD_KEYWORD_INDEX_VERSION),
                    ("n_chunks", str(len(chunks))),
                    ("corpus_fingerprint", corpus_fingerprint or ""),
                ],
            )
            connection.commit()
            quick_check = connection.execute("PRAGMA quick_check").fetchone()
            if quick_check != ("ok",):
                raise RuntimeError(f"field-keyword SQLite quick_check failed: {quick_check}")
            invalid_chunk = connection.execute(
                "SELECT 1 FROM field_rows WHERE chunk_id < 0 OR chunk_id >= ? LIMIT 1",
                (len(chunks),),
            ).fetchone()
            if invalid_chunk is not None:
                raise RuntimeError("field-keyword index contains an out-of-range chunk id")
        except Exception:
            connection.close()
            staged_path.unlink(missing_ok=True)
            raise
        else:
            connection.close()

        self._staged_path = staged_path
        self._chunks = chunks
        self.n_chunks = len(chunks)
        self.corpus_fingerprint = corpus_fingerprint
        self.version = FIELD_KEYWORD_INDEX_VERSION

    def save(self) -> None:
        if self._staged_path is None:
            return
        self._staged_path.replace(self.path)
        self._staged_path = None

    def load(
        self,
        *,
        expected_chunks: int | None = None,
        expected_fingerprint: str | None = None,
    ) -> bool:
        if not self.path.exists():
            return False
        try:
            with _open_field_index(self.path) as connection:
                metadata = dict(connection.execute("SELECT key, value FROM metadata"))
        except (OSError, sqlite3.DatabaseError):
            return False
        n_chunks = int(metadata.get("n_chunks", 0))
        if expected_chunks is not None and n_chunks != expected_chunks:
            return False
        corpus_fingerprint = metadata.get("corpus_fingerprint") or None
        if expected_fingerprint is not None and corpus_fingerprint != expected_fingerprint:
            return False
        if metadata.get("version") != FIELD_KEYWORD_INDEX_VERSION:
            return False
        self.n_chunks = n_chunks
        self.corpus_fingerprint = corpus_fingerprint
        self.version = metadata["version"]
        return True

    def search(self, spec: FieldKeywordSpec | dict | list | str, top_k: int = 50) -> list[tuple[int, float]]:
        keyword_spec = coerce_keyword_spec(spec)
        _validate_keyword_spec(keyword_spec)
        active_path = self._staged_path or self.path
        if (
            self.n_chunks == 0
            or self._chunks is None
            or len(self._chunks) != self.n_chunks
            or not active_path.exists()
            or not keyword_spec.concepts
        ):
            return []

        with _open_field_index(active_path) as connection:
            if not self._connection_matches_generation(connection):
                raise RuntimeError("field-keyword index changed generation while the corpus was loaded")
            candidates = self._candidate_indices(connection, keyword_spec)
        ranked: list[tuple[int, float]] = []
        for index in candidates:
            record = _record_from_chunk(self._chunks[index])
            score, _matches = self.score_record(record, keyword_spec)
            if score > 0:
                ranked.append((index, score))
        ranked.sort(key=lambda item: item[1], reverse=True)
        return ranked[:top_k]

    def explain(self, index: int, spec: FieldKeywordSpec | dict | list | str) -> dict[str, Any]:
        keyword_spec = coerce_keyword_spec(spec)
        active_path = self._staged_path or self.path
        if (
            index < 0
            or index >= self.n_chunks
            or self._chunks is None
            or len(self._chunks) != self.n_chunks
            or not active_path.exists()
        ):
            return {"score": 0.0, "matches": []}
        record = _record_from_chunk(self._chunks[index])
        score, matches = self.score_record(record, keyword_spec)
        return {"score": score, "matches": [match.to_dict() for match in matches]}

    def _candidate_indices(self, connection: sqlite3.Connection, spec: FieldKeywordSpec) -> list[int]:
        candidates: set[int] = set()
        requests: dict[tuple[str, str, tuple[str, ...]], set[str] | None] = {}
        for concept in spec.concepts:
            requested_fields = concept.target_fields or DEFAULT_TARGET_FIELDS
            concept_fields: set[str] | None = set()
            for requested_field in requested_fields:
                field_names = _stored_field_names(requested_field)
                if field_names is None:
                    concept_fields = None
                    break
                concept_fields.update(field_names)

            for form in concept.surface_forms:
                needle = normalize_text(form.text)
                if not needle:
                    continue
                match_type = form.match if form.match in {"phrase", "substring", "token"} else "phrase"
                cohits = tuple(
                    sorted({normalize_text(item) for item in form.requires_cohit if normalize_text(item)})
                )
                request_key = (needle, match_type, cohits)
                if request_key not in requests:
                    requests[request_key] = None if concept_fields is None else set(concept_fields)
                elif requests[request_key] is not None:
                    if concept_fields is None:
                        requests[request_key] = None
                    else:
                        requests[request_key].update(concept_fields)

        scan_requests: dict[str, tuple[str, ...] | None] = {}
        for (needle, match_type, cohits), requested_fields in requests.items():
            field_names = None if requested_fields is None else tuple(sorted(requested_fields))
            request_candidates: set[int] | None = None
            if len(needle) < 3:
                if match_type == "token":
                    request_candidates = _query_short_token_candidates(connection, needle, field_names)
                else:
                    if needle not in scan_requests:
                        scan_requests[needle] = field_names
                    else:
                        scan_requests[needle] = _merge_field_names(scan_requests[needle], field_names)
                    continue
            else:
                try:
                    request_candidates = _query_field_candidates(connection, needle, field_names)
                except sqlite3.DatabaseError:
                    if needle not in scan_requests:
                        scan_requests[needle] = field_names
                    else:
                        scan_requests[needle] = _merge_field_names(scan_requests[needle], field_names)
                    continue

            if request_candidates is not None and cohits and all(len(cohit) >= 3 for cohit in cohits):
                try:
                    cohit_candidates: set[int] = set()
                    for cohit in cohits:
                        cohit_candidates.update(_query_field_candidates(connection, cohit, None))
                    request_candidates.intersection_update(cohit_candidates)
                except sqlite3.DatabaseError:
                    pass
            if request_candidates is not None:
                candidates.update(request_candidates)
        if scan_requests:
            candidates.update(self._scan_candidate_requests(scan_requests))
        return sorted(candidates)

    def _scan_candidates(self, needle: str, field_names: tuple[str, ...] | None) -> set[int]:
        """Exact bounded-memory fallback, including terms too short for trigram FTS."""
        return self._scan_candidate_requests({needle: field_names})

    def _scan_candidate_requests(
        self,
        requests: dict[str, tuple[str, ...] | None],
    ) -> set[int]:
        """Scan the corpus once for any number of non-trigram surface forms."""
        matches: set[int] = set()
        if self._chunks is None:
            return matches
        needs_all_fields = any(field_names is None for field_names in requests.values())
        selected_fields = {
            field_name
            for field_names in requests.values()
            if field_names is not None
            for field_name in field_names
        }
        for index, chunk in enumerate(self._chunks):
            if needs_all_fields:
                record = _record_from_chunk(chunk)
                field_values = record.fields
            else:
                field_values = {
                    field_name: _stored_field_value_from_chunk(chunk, field_name)
                    for field_name in selected_fields
                }
            for needle, field_names in requests.items():
                values = field_values.values() if field_names is None else (
                    field_values.get(field_name, "") for field_name in field_names
                )
                if any(needle in value for value in values):
                    matches.add(index)
                    break
        return matches

    def _connection_matches_generation(self, connection: sqlite3.Connection) -> bool:
        try:
            metadata = dict(connection.execute("SELECT key, value FROM metadata"))
        except sqlite3.DatabaseError:
            return False
        return (
            metadata.get("version") == self.version
            and int(metadata.get("n_chunks", 0)) == self.n_chunks
            and (metadata.get("corpus_fingerprint") or None) == self.corpus_fingerprint
        )

    def score_record(self, record: FieldKeywordRecord, spec: FieldKeywordSpec) -> tuple[float, list[FieldKeywordMatch]]:
        total_score = 0.0
        matches: list[FieldKeywordMatch] = []
        for concept in spec.concepts:
            concept_score = 0.0
            concept_matches: list[FieldKeywordMatch] = []
            fields = concept.target_fields or DEFAULT_TARGET_FIELDS
            concept_cap = _concept_cap(concept, fields)

            for requested_field, field_weight in fields.items():
                for actual_field, field_text in _field_texts(record, requested_field):
                    if not field_text:
                        continue
                    for form in concept.surface_forms:
                        if not _cohit_satisfied(record, form):
                            continue
                        count = _match_count(field_text, form)
                        if count <= 0:
                            continue
                        score = (
                            float(concept.query_weight)
                            * max(0.0, float(form.weight))
                            * max(0.0, float(field_weight))
                            * _discounted_occurrences(
                                count,
                                decay=spec.occurrence_decay,
                                max_occurrences=spec.max_occurrences_per_field,
                            )
                        )
                        if score <= 0:
                            continue
                        concept_score += score
                        concept_matches.append(
                            FieldKeywordMatch(
                                concept=concept.concept,
                                field=actual_field,
                                surface_form=form.text,
                                count=count,
                                score=score,
                            )
                        )

            if concept_cap > 0:
                concept_score = min(concept_score, concept_cap)
            total_score += concept_score
            matches.extend(concept_matches)
        return total_score, matches


@contextmanager
def _open_field_index(path: Path):
    uri = f"{Path(path).resolve().as_uri()}?mode=ro&immutable=1"
    connection = sqlite3.connect(uri, uri=True)
    try:
        connection.execute("PRAGMA query_only=ON")
        connection.execute("PRAGMA cache_size=-8192")
        connection.execute("PRAGMA mmap_size=0")
        yield connection
    finally:
        connection.close()


def _stored_field_names(requested_field: str) -> tuple[str, ...] | None:
    requested = str(requested_field or "").strip()
    if requested == "*":
        return None
    canonical = SPECIAL_FIELDS.get(requested.lower(), requested)
    if canonical == "Gene_Name":
        return ("Gene_Name", "__gene_name__")
    return (canonical,)


def _merge_field_names(
    current: tuple[str, ...] | None,
    incoming: tuple[str, ...] | None,
) -> tuple[str, ...] | None:
    if current is None or incoming is None:
        return None
    return tuple(sorted(set(current).union(incoming)))


def _query_field_candidates(
    connection: sqlite3.Connection,
    needle: str,
    field_names: tuple[str, ...] | None,
) -> set[int]:
    # Quoting turns the normalized surface form into a literal trigram phrase
    # and prevents model-generated punctuation from becoming FTS syntax.
    fts_query = '"' + needle.replace('"', '""') + '"'
    # Pin the FTS virtual table as the outer loop. With a regular JOIN SQLite
    # can choose the field-name index first and execute the FTS lookup millions
    # of times. Python already de-duplicates chunk ids, so DISTINCT is needless.
    sql = (
        "SELECT rows.chunk_id "
        "FROM field_fts CROSS JOIN field_rows AS rows ON rows.rowid = field_fts.rowid "
        "WHERE field_fts MATCH ?"
    )
    params: list[Any] = [fts_query]
    if field_names is not None:
        placeholders = ", ".join("?" for _ in field_names)
        sql += f" AND rows.field_name IN ({placeholders})"
        params.extend(field_names)
    return {int(row[0]) for row in connection.execute(sql, params)}


def _query_short_token_candidates(
    connection: sqlite3.Connection,
    needle: str,
    field_names: tuple[str, ...] | None,
) -> set[int]:
    """Use the token FTS table for one- and two-character exact tokens.

    Trigram FTS cannot represent these identifiers, while scanning every
    canonical chunk makes common abbreviations such as ``GA`` take seconds.
    The unicode tokenizer only supplies a candidate superset; ``score_record``
    still applies the stricter Python token-boundary and co-hit semantics.
    """

    fts_query = '"' + needle.replace('"', '""') + '"'
    sql = (
        "SELECT rows.chunk_id "
        "FROM field_token_fts CROSS JOIN field_rows AS rows "
        "ON rows.rowid = field_token_fts.rowid "
        "WHERE field_token_fts MATCH ?"
    )
    params: list[Any] = [fts_query]
    if field_names is not None:
        placeholders = ", ".join("?" for _ in field_names)
        sql += f" AND rows.field_name IN ({placeholders})"
        params.extend(field_names)
    return {int(row[0]) for row in connection.execute(sql, params)}


def coerce_keyword_spec(value: FieldKeywordSpec | dict | list | str | None) -> FieldKeywordSpec:
    if isinstance(value, FieldKeywordSpec):
        return value
    if value is None:
        return FieldKeywordSpec(concepts=())
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return FieldKeywordSpec(concepts=())
        if stripped.startswith("{") or stripped.startswith("["):
            try:
                return coerce_keyword_spec(json.loads(stripped))
            except json.JSONDecodeError:
                pass
        return build_keyword_spec_from_query(stripped)
    if isinstance(value, list):
        concepts = tuple(_coerce_concept(item) for item in value)
        return FieldKeywordSpec(concepts=tuple(concept for concept in concepts if concept.surface_forms))
    if isinstance(value, dict):
        if "concepts" in value:
            concepts_value = value.get("concepts") or []
            concepts = tuple(_coerce_concept(item) for item in concepts_value)
            return FieldKeywordSpec(
                concepts=tuple(concept for concept in concepts if concept.surface_forms),
                occurrence_decay=float(value.get("occurrence_decay", 0.5)),
                max_occurrences_per_field=int(value.get("max_occurrences_per_field", 8)),
            )
        concept = _coerce_concept(value)
        return FieldKeywordSpec(concepts=(concept,) if concept.surface_forms else ())
    return FieldKeywordSpec(concepts=())


def _validate_keyword_spec(spec: FieldKeywordSpec) -> None:
    if len(spec.concepts) > MAX_CONCEPTS:
        raise ValueError(f"field keyword spec supports at most {MAX_CONCEPTS} concepts")
    if not 0.0 <= float(spec.occurrence_decay) <= 1.0:
        raise ValueError("field keyword occurrence_decay must be between 0 and 1")
    if not 1 <= int(spec.max_occurrences_per_field) <= 100:
        raise ValueError("field keyword max_occurrences_per_field must be between 1 and 100")

    total_forms = 0
    for concept in spec.concepts:
        total_forms += len(concept.surface_forms)
        if total_forms > MAX_SURFACE_FORMS:
            raise ValueError(f"field keyword spec supports at most {MAX_SURFACE_FORMS} surface forms")
        if len(concept.target_fields) > MAX_TARGET_FIELDS_PER_CONCEPT:
            raise ValueError(
                f"field keyword concept supports at most {MAX_TARGET_FIELDS_PER_CONCEPT} target fields"
            )
        numeric_values = [
            concept.query_weight,
            concept.concept_cap_multiplier,
            *concept.target_fields.values(),
        ]
        if any(not isinstance(value, int | float) or not float("-inf") < float(value) < float("inf") for value in numeric_values):
            raise ValueError("field keyword weights must be finite numbers")
        for form in concept.surface_forms:
            if len(form.text) > MAX_SURFACE_TEXT_CHARS:
                raise ValueError(
                    f"field keyword surface text supports at most {MAX_SURFACE_TEXT_CHARS} characters"
                )
            if len(form.requires_cohit) > MAX_COHIT_TERMS_PER_FORM:
                raise ValueError(
                    f"field keyword surface form supports at most {MAX_COHIT_TERMS_PER_FORM} co-hit terms"
                )
            if any(len(item) > MAX_SURFACE_TEXT_CHARS for item in form.requires_cohit):
                raise ValueError("field keyword co-hit text is too long")
            if not float("-inf") < float(form.weight) < float("inf"):
                raise ValueError("field keyword weights must be finite numbers")


def build_keyword_spec_from_query(query: str) -> FieldKeywordSpec:
    """Weak fallback when no agent-generated spec is supplied.

    The agent-generated JSON is the intended path. This fallback only keeps the
    field keyword layer useful in diagnostics or behind the env feature flag.
    """

    tokens = []
    quoted = re.findall(r"['\"]([^'\"]{2,80})['\"]", query)
    latin_species = re.findall(r"\b[A-Z][a-z]+(?:\s+[a-z][a-z.-]+){1,2}\b", query)
    tokens.extend(quoted)
    tokens.extend(latin_species)
    tokens.extend(token for token in tokenize(query) if len(token) >= 3)

    seen: set[str] = set()
    concepts: list[ConceptSpec] = []
    for token in tokens[:24]:
        key = normalize_text(token)
        if not key or key in seen:
            continue
        seen.add(key)
        concepts.append(
            ConceptSpec(
                concept=f"query_term:{token}",
                query_weight=1.0,
                surface_forms=(SurfaceForm(text=token, weight=1.0, match="token" if len(token) <= 6 else "phrase"),),
                target_fields=DEFAULT_TARGET_FIELDS,
                concept_cap_multiplier=1.5,
            )
        )
    return FieldKeywordSpec(concepts=tuple(concepts))


def normalize_text(value: Any) -> str:
    text = unicodedata.normalize("NFKC", str(value or ""))
    text = text.replace("\u2010", "-").replace("\u2011", "-").replace("\u2012", "-")
    text = text.replace("\u2013", "-").replace("\u2014", "-").replace("\u2212", "-")
    return re.sub(r"\s+", " ", text).strip().lower()


def _coerce_concept(value: Any) -> ConceptSpec:
    if isinstance(value, ConceptSpec):
        return value
    if not isinstance(value, dict):
        return ConceptSpec(concept="", surface_forms=())

    concept = str(value.get("concept") or value.get("name") or "").strip()
    query_weight = float(value.get("query_weight", value.get("weight", 1.0)) or 1.0)
    forms_value = value.get("surface_forms", value.get("candidates", value.get("aliases", [])))
    surface_forms = tuple(_coerce_surface_form(item) for item in forms_value)
    surface_forms = tuple(form for form in surface_forms if normalize_text(form.text))
    return ConceptSpec(
        concept=concept or "unnamed_concept",
        query_weight=query_weight,
        surface_forms=surface_forms,
        target_fields=_coerce_target_fields(value.get("target_fields")),
        concept_cap_multiplier=float(value.get("concept_cap_multiplier", 2.0) or 2.0),
    )


def _coerce_surface_form(value: Any) -> SurfaceForm:
    if isinstance(value, SurfaceForm):
        return value
    if isinstance(value, str):
        return SurfaceForm(text=value)
    if not isinstance(value, dict):
        return SurfaceForm(text="")
    return SurfaceForm(
        text=str(value.get("text") or value.get("term") or "").strip(),
        weight=float(value.get("weight", 1.0) or 1.0),
        match=str(value.get("match") or "phrase").strip().lower(),
        requires_cohit=tuple(str(item) for item in value.get("requires_cohit", ()) if str(item).strip()),
    )


def _coerce_target_fields(value: Any) -> dict[str, float]:
    if not value:
        return {}
    if isinstance(value, dict):
        return {str(key): float(weight) for key, weight in value.items()}
    if isinstance(value, list):
        return {str(item): 1.0 for item in value if str(item).strip()}
    return {}


def _record_from_chunk(chunk: Any) -> FieldKeywordRecord:
    metadata = getattr(chunk, "metadata", None)
    metadata = metadata if isinstance(metadata, dict) else {}

    fields: dict[str, str] = {}
    for key, value in metadata.items():
        text = _value_to_text(value)
        if text:
            fields[str(key)] = normalize_text(text)

    fields.setdefault("Gene_Name", normalize_text(getattr(chunk, "gene_name", "")))
    fields["__gene_name__"] = normalize_text(getattr(chunk, "gene_name", ""))
    fields["__paper_title__"] = normalize_text(getattr(chunk, "paper_title", ""))
    fields["__journal__"] = normalize_text(getattr(chunk, "journal", ""))
    fields["__doi__"] = normalize_text(getattr(chunk, "doi", ""))
    fields["__content__"] = normalize_text(getattr(chunk, "content", ""))
    fields["__chunk_type__"] = normalize_text(getattr(chunk, "chunk_type", ""))
    fields["__gene_type__"] = normalize_text(getattr(chunk, "gene_type", ""))
    fields["__source_fields__"] = normalize_text("; ".join(str(item) for item in getattr(chunk, "source_fields", []) or []))
    fields["__relations__"] = normalize_text(json.dumps(getattr(chunk, "relations", {}) or {}, ensure_ascii=False, sort_keys=True))

    all_text = "\n".join(text for text in fields.values() if text)
    return FieldKeywordRecord(fields=fields, all_text=all_text)


def _stored_field_value_from_chunk(chunk: Any, field_name: str) -> str:
    """Reconstruct one stored field without projecting every metadata column."""
    metadata = getattr(chunk, "metadata", None)
    metadata = metadata if isinstance(metadata, dict) else {}
    if field_name == "Gene_Name":
        metadata_value = _value_to_text(metadata.get("Gene_Name"))
        return normalize_text(metadata_value or getattr(chunk, "gene_name", ""))
    if field_name == "__gene_name__":
        return normalize_text(getattr(chunk, "gene_name", ""))
    if field_name == "__paper_title__":
        return normalize_text(getattr(chunk, "paper_title", ""))
    if field_name == "__journal__":
        return normalize_text(getattr(chunk, "journal", ""))
    if field_name == "__doi__":
        return normalize_text(getattr(chunk, "doi", ""))
    if field_name == "__content__":
        return normalize_text(getattr(chunk, "content", ""))
    if field_name == "__chunk_type__":
        return normalize_text(getattr(chunk, "chunk_type", ""))
    if field_name == "__gene_type__":
        return normalize_text(getattr(chunk, "gene_type", ""))
    if field_name == "__source_fields__":
        return normalize_text("; ".join(str(item) for item in getattr(chunk, "source_fields", []) or []))
    if field_name == "__relations__":
        return normalize_text(
            json.dumps(getattr(chunk, "relations", {}) or {}, ensure_ascii=False, sort_keys=True)
        )
    return normalize_text(_value_to_text(metadata.get(field_name)))


def _value_to_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return "" if value.strip().lower() in INVALID_VALUES else value.strip()
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "; ".join(_value_to_text(item) for item in value if _value_to_text(item))
    if isinstance(value, dict):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value).strip()


def _field_texts(record: FieldKeywordRecord, requested_field: str) -> list[tuple[str, str]]:
    requested = str(requested_field or "").strip()
    if not requested:
        return []
    if requested == "*":
        return [("*", record.all_text)]

    canonical = SPECIAL_FIELDS.get(requested.lower(), requested)
    if canonical == "Gene_Name":
        values = []
        if record.fields.get("Gene_Name"):
            values.append(("Gene_Name", record.fields["Gene_Name"]))
        if record.fields.get("__gene_name__"):
            values.append(("gene_name", record.fields["__gene_name__"]))
        return values
    if canonical in record.fields:
        return [(requested, record.fields[canonical])]
    return []


def _cohit_satisfied(record: FieldKeywordRecord, form: SurfaceForm) -> bool:
    if not form.requires_cohit:
        return True
    return any(normalize_text(item) in record.all_text for item in form.requires_cohit)


def _match_count(field_text: str, form: SurfaceForm) -> int:
    needle = normalize_text(form.text)
    if not needle:
        return 0
    match_type = form.match if form.match in {"phrase", "substring", "token"} else "phrase"
    if match_type in {"phrase", "substring"}:
        return field_text.count(needle)
    pattern = re.compile(rf"(?<![\w.-]){re.escape(needle)}(?![\w.-])", flags=re.UNICODE)
    return len(pattern.findall(field_text))


def _discounted_occurrences(count: int, *, decay: float, max_occurrences: int) -> float:
    count = max(0, min(int(count), int(max_occurrences)))
    decay = min(max(float(decay), 0.0), 1.0)
    return sum(decay**index for index in range(count))


def _concept_cap(concept: ConceptSpec, fields: dict[str, float]) -> float:
    if not fields or not concept.surface_forms:
        return 0.0
    max_field = max(max(0.0, float(weight)) for weight in fields.values())
    max_form = max(max(0.0, float(form.weight)) for form in concept.surface_forms)
    return (
        max(0.0, float(concept.query_weight))
        * max_field
        * max_form
        * max(0.0, float(concept.concept_cap_multiplier))
    )
